### ISSUE TITLE
geoalchemy2 does not support spatialite

### ISSUE THREAD

**Issue by cholin** [cholin/aktionskarten-backend#1]
For development we want to use spatialite instead of postgis. With that developers do not need a local postgis database. Sadly geoalchemy2 dropped support for spatialite:

> Note
> GeoAlchemy 2 doesn’t currently support other dialects than PostgreSQL/PostGIS. Supporting Oracle Locator in the previous series was the main contributor to code complexity. So it is currently not clear whether we want to go there again.

(see https://geoalchemy-2.readthedocs.org/en/0.2.6/)

Either we use geoalchemy (which has support for spatialite but seems not that flexible in their abstraction layer) or we use postgis as well for our development process.

**Comment by cholin** [comment]
We have nearly not written any code so we could as well switch our framework if we want to. GeoDjango seems to support multiple backends like geoalchemy1.

**Comment by fupduck** [comment]
changed to django
